######################## default configuration ####################
baseURL = "https://santander.edu.ec/"
title = "Unidad Educativa Santander"
theme = "educenter-hugo"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "educenter" # get your shortname form here : https://disqus.com
# disable language
defaultContentLanguage = "es"
disableLanguages = ['en']# desable language from here


############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"


#################### default parameters ################################
[params]
logo = "images/logo.png"
# Meta data
description = "Unidad Educativa Particular PCEI a Distancia Santander"
author = "Said Neder"
# contact info
address = "Cdla. Los Álamos MZ 4 Solar #4, Guayaquil, Ecuador"
mobile = "0992235197"
email = "santander.educacionadistancia@gmail.com"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "" # your id
# top header
top_header = true

# Preloader
[params.preloader]
enable = false
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

# Subscription
[params.subscription]
enable = false
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# google map
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png" # marker size 37*55 px

# cookies
[params.cookies]
enable = true
expire_days = 2
  
############################# social site ########################
[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "#"


################################### English language #####################################
# [Languages.en]
# languageName = "En"
# languageCode = "en-us"
# contentDir = "content/english"
# weight = 1
# home = "Home"
# # copyright
# copyright = "Copyright &copy; 2021 a hugo theme by [Themefisher](https://themefisher.com/hugo-themes/)"



# ################### English navigation ####################

# # main menu
# [[Languages.en.menu.main]]
# name = "About"
# url = "about/"
# weight = 1

# [[Languages.en.menu.main]]
# name = "course"
# url = "course/"
# weight = 2

# [[Languages.en.menu.main]]
# weight = 3
# name = "Pages"
# hasChildren = true

#   [[Languages.en.menu.main]]
#   parent = "Pages"
#   name = "teacher"
#   url = "teacher/"

#   [[Languages.en.menu.main]]
#   parent = "Pages"
#   name = "notice"
#   url = "notice/"

#   [[Languages.en.menu.main]]
#   parent = "Pages"
#   name = "event"
#   url = "event/"

#   [[Languages.en.menu.main]]
#   parent = "Pages"
#   name = "scholarship"
#   url = "scholarship/"

#   [[Languages.en.menu.main]]
#   parent = "Pages"
#   name = "research"
#   url = "research/"
  
# [[Languages.en.menu.main]]
# name = "blog"
# url = "blog/"
# weight = 4
  
# [[Languages.en.menu.main]]
# name = "Contact"
# url = "contact/"
# weight = 5


# # footer menu

# [[Languages.en.menu.footer]]
# name = "teacher"
# url = "teacher/"

# [[Languages.en.menu.footer]]
# name = "notice"
# url = "notice/"

# [[Languages.en.menu.footer]]
# name = "event"
# url = "event/"

# [[Languages.en.menu.footer]]
# name = "scholarship"
# url = "scholarship/"

# [[Languages.en.menu.footer]]
# name = "research"
# url = "research/"



################################### Spanish language #####################################
[Languages.es]
languageName = "Es"
languageCode = "es-es"
contentDir = "content/spanish"
weight = 1
home = "Casa"
# copyright
copyright = "Copyright &copy; 2021 spanish"



################### Spanish navigation ####################

# main menu
[[Languages.es.menu.main]]
name = "Sobre Nosotros"
weight = 1
hasChildren = true

[[Languages.es.menu.main]]
parent = "Sobre Nosotros"
name = "Quiénes somos"
url = "about/"

[[Languages.es.menu.main]]
name = "Cursos"
url = "course/"
weight = 2

[[Languages.es.menu.main]]
parent = "Sobre Nosotros"
name = "Profesores"
url = "teacher/"

[[Languages.es.menu.main]]
parent = "Sobre Nosotros"
name = "Noticias"
url = "notice/"

[[Languages.es.menu.main]]
parent = "Sobre Nosotros"
name = "Eventos"
url = "event/"

[[Languages.es.menu.main]]
parent = "Sobre Nosotros"
name = "Blog"
url = "blog/"
  
[[Languages.es.menu.main]]
name = "Matriculación"
url = "https://docs.google.com/forms/d/e/1FAIpQLSe5aC03oZVfSqqIfdmtYFApDTJrUCVE8RBjBdoqs4KfafNiMw/viewform?usp=sf_link"
weight = 3


# footer menu

[[Languages.es.menu.footer]]
name = "Profesores"
url = "teacher/"

[[Languages.es.menu.footer]]
name = "Noticias"
url = "notice/"

[[Languages.es.menu.footer]]
name = "Eventos"
url = "event/"